artifacts_roots: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url:  https://drive.google.com/file/d/1GRD4oa9ueXtCYQXY24AfWN9SOQc41at8/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion